apiVersion: v1
kind: Service
metadata:
    name: demo-service
    labels:
        name: demo-service
        app: demo-project-app
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
    selector:
        name: demo-app-pod
        app: demo-project-app