apiVersion: apps/v1
kind: Deployment
metadata:
    name: demo-app-deploy
    labels:
        name: demo-app-deploy
        app: demo-project-app
spec:
    replicas: 1
    selector:
        matchLabels:
            name: demo-app-pod
            app: demo-project-app
    template:
        metadata:
            name: demo-app-pod
            labels:
                name: demo-app-pod
                app: demo-project-app
        spec:
            containers:
                - name: demo-app
                  image: svdevops07/kuber_app:v0.1
                  ports:
                      - containerPort: 80